/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package battleship;

import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author ASUS R.O.G
 */
public class InGame extends javax.swing.JFrame {
    private JButton[][] papan1 = new JButton[10][10];
    
    public InGame() {
        initComponents();
        setPapan();
    }
    
    public void setPapan(){ //membuat papan kotak
        int posisiX=0;
        int posisiY=0;
        int size=35;
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                //papan untuk player1
                papan1[i][j] = new JButton();
                papan1[i][j].setBackground(Color.white);
                papan1[i][j].setSize(size, size);
                papan1[i][j].setLocation(posisiX, posisiY);
                player1.add(papan1[i][j]);
                posisiX+=35;
            }
            posisiX=0;
            posisiY+=35;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        keluar = new javax.swing.JButton();
        player1 = new javax.swing.JPanel();
        cruiser = new javax.swing.JButton();
        carier = new javax.swing.JButton();
        battleship = new javax.swing.JButton();
        bgMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        keluar.setBackground(new java.awt.Color(255, 0, 0));
        keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/TOMBOL/keluarGame.png"))); // NOI18N
        keluar.setBorder(null);
        keluar.setBorderPainted(false);
        keluar.setMargin(new java.awt.Insets(2, 8, 2, 8));
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(996, 10, 90, 30);

        player1.setLayout(null);

        cruiser.setBackground(new java.awt.Color(255, 255, 255));
        cruiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warfare/cruiser.png"))); // NOI18N
        cruiser.setBorder(null);
        cruiser.setBorderPainted(false);
        cruiser.setContentAreaFilled(false);
        cruiser.setFocusPainted(false);
        player1.add(cruiser);
        cruiser.setBounds(105, 0, 35, 140);

        carier.setBackground(new java.awt.Color(255, 255, 255));
        carier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warfare/carier.png"))); // NOI18N
        carier.setBorder(null);
        carier.setBorderPainted(false);
        carier.setContentAreaFilled(false);
        carier.setFocusPainted(false);
        player1.add(carier);
        carier.setBounds(35, 0, 70, 210);

        battleship.setBackground(new java.awt.Color(255, 255, 255));
        battleship.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warfare/battleship.png"))); // NOI18N
        battleship.setBorder(null);
        battleship.setBorderPainted(false);
        battleship.setContentAreaFilled(false);
        battleship.setFocusPainted(false);
        player1.add(battleship);
        battleship.setBounds(0, 0, 35, 210);

        getContentPane().add(player1);
        player1.setBounds(110, 190, 350, 350);

        bgMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Background.jpg"))); // NOI18N
        getContentPane().add(bgMenu);
        bgMenu.setBounds(0, 0, 1100, 650);

        setSize(new java.awt.Dimension(1100, 650));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton battleship;
    private javax.swing.JLabel bgMenu;
    private javax.swing.JButton carier;
    private javax.swing.JButton cruiser;
    private javax.swing.JButton keluar;
    private javax.swing.JPanel player1;
    // End of variables declaration//GEN-END:variables
}
