/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package battleship;

import javax.swing.SwingConstants;

/**
 *
 * @author ASUS R.O.G
 */
public class Kalah extends javax.swing.JFrame {

    /**
     * Creates new form LoadingGame
     */
    public Kalah() {
        initComponents();
        skor.setHorizontalAlignment(SwingConstants.CENTER);
        skor.setText(Integer.toString(Permainan.point));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        skor = new javax.swing.JLabel();
        namaPemain = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        bgLoading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        skor.setFont(new java.awt.Font("Bebas Neue", 1, 100)); // NOI18N
        skor.setForeground(new java.awt.Color(255, 255, 255));
        skor.setFocusable(false);
        skor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(skor);
        skor.setBounds(410, 200, 300, 150);

        namaPemain.setFont(new java.awt.Font("Bebas Neue", 3, 70)); // NOI18N
        getContentPane().add(namaPemain);
        namaPemain.setBounds(385, 370, 350, 100);

        simpan.setBackground(new java.awt.Color(0, 255, 0));
        simpan.setFont(new java.awt.Font("Bebas Neue", 3, 30)); // NOI18N
        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan);
        simpan.setBounds(490, 500, 150, 50);

        bgLoading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kalah.jpg"))); // NOI18N
        getContentPane().add(bgLoading);
        bgLoading.setBounds(0, 0, 1100, 650);

        setSize(new java.awt.Dimension(1100, 650));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        String nama = namaPemain.getText();
        int score = Integer.parseInt(skor.getText());
        Database db = new Database(nama, score);
        MenuGame mg = new MenuGame();
        mg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_simpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLoading;
    private javax.swing.JTextField namaPemain;
    private javax.swing.JButton simpan;
    private javax.swing.JLabel skor;
    // End of variables declaration//GEN-END:variables
}
