/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package battleship;

import java.awt.Color;
import java.awt.Container;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author ASUS R.O.G
 */
public class NewPanel extends JFrame {

    private Container konten;
    
    //membuat JButton seperti matriks yang memiliki ukuran 10x10
    private JButton[][] papan = new JButton[10][10];
    
    public NewPanel(){
        konten = getContentPane();
        konten.setLayout(new GridLayout(10,10));
//        ButtonHandler kontrol = new ButtonHandler();
        
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                papan[i][j] = new JButton();
                konten.add(papan[i][j]);
                papan[i][j].setBackground(Color.white);
            }
        }
    }
    
    public static void main(String[] args){
        NewPanel np = new NewPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName(""); // NOI18N
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
