/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package battleship;

import java.awt.Font;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author ASUS R.O.G
 */
public class ScoreBoard extends javax.swing.JFrame {
    private static final String url = "jdbc:mysql://localhost/Battleship";
    private static final String jdbc = "com.mysql.jdbc.Driver";
    private static final String user = "root";
    private static final String password = "";
    private final String sql = "SELECT * FROM pemain ORDER BY point DESC LIMIT 3";
    
    private static Connection koneksi;
    private static Statement stat;
    private static ResultSet rs;
    
    private int posisiX = 20;
    private int posisiY = 30;
    public ScoreBoard() {
        int i=0;
        initComponents();
        
        try {
            Database db = new Database(sql);
            rs = db.getRS();
            while(rs.next()){
                if (i==0) {
                    nama.setText(rs.getString("nama"));
                    point.setText(rs.getString("point"));
                }else if (i==1) {
                    nama1.setText(rs.getString("nama"));
                    point1.setText(rs.getString("point"));
                }else if (i==2) {
                    nama2.setText(rs.getString("nama"));
                    point2.setText(rs.getString("point"));
                }
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(ScoreBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void diskonek(){
        try {
            stat.close();
            koneksi.close();
        } catch (SQLException ex) {
            Logger.getLogger(ScoreBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kembali = new javax.swing.JButton();
        panel1 = new javax.swing.JPanel();
        nama = new javax.swing.JLabel();
        nama1 = new javax.swing.JLabel();
        nama2 = new javax.swing.JLabel();
        point = new javax.swing.JLabel();
        point1 = new javax.swing.JLabel();
        point2 = new javax.swing.JLabel();
        bgMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        kembali.setFont(new java.awt.Font("Rosewood Std Regular", 3, 36)); // NOI18N
        kembali.setForeground(new java.awt.Color(0, 0, 255));
        kembali.setText("KEMBALI");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali);
        kembali.setBounds(10, 10, 190, 60);

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setFocusable(false);
        panel1.setOpaque(false);
        panel1.setLayout(null);

        nama.setBackground(new java.awt.Color(255, 255, 255));
        nama.setFont(new java.awt.Font("Bebas Neue", 0, 50)); // NOI18N
        nama.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nama.setLabelFor(panel1);
        panel1.add(nama);
        nama.setBounds(20, 20, 230, 70);

        nama1.setBackground(new java.awt.Color(255, 255, 255));
        nama1.setFont(new java.awt.Font("Bebas Neue", 0, 50)); // NOI18N
        nama1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nama1.setLabelFor(panel1);
        panel1.add(nama1);
        nama1.setBounds(20, 90, 230, 70);

        nama2.setBackground(new java.awt.Color(255, 255, 255));
        nama2.setFont(new java.awt.Font("Bebas Neue", 0, 50)); // NOI18N
        nama2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nama2.setLabelFor(panel1);
        panel1.add(nama2);
        nama2.setBounds(20, 180, 230, 70);

        point.setBackground(new java.awt.Color(255, 255, 255));
        point.setFont(new java.awt.Font("Bebas Neue", 0, 50)); // NOI18N
        point.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel1.add(point);
        point.setBounds(270, 20, 230, 70);

        point1.setBackground(new java.awt.Color(255, 255, 255));
        point1.setFont(new java.awt.Font("Bebas Neue", 0, 50)); // NOI18N
        point1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel1.add(point1);
        point1.setBounds(270, 90, 230, 70);

        point2.setBackground(new java.awt.Color(255, 255, 255));
        point2.setFont(new java.awt.Font("Bebas Neue", 0, 50)); // NOI18N
        point2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel1.add(point2);
        point2.setBounds(270, 180, 230, 70);

        getContentPane().add(panel1);
        panel1.setBounds(300, 180, 500, 290);

        bgMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/scoreboard.jpg"))); // NOI18N
        getContentPane().add(bgMenu);
        bgMenu.setBounds(0, 0, 1100, 650);

        setSize(new java.awt.Dimension(1100, 650));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        MenuGame mg = new MenuGame();
        mg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgMenu;
    private javax.swing.JButton kembali;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nama1;
    private javax.swing.JLabel nama2;
    private javax.swing.JPanel panel1;
    private javax.swing.JLabel point;
    private javax.swing.JLabel point1;
    private javax.swing.JLabel point2;
    // End of variables declaration//GEN-END:variables
}
